### PR TITLE
fix: bottomsheet-1.3.1.aar incorrectly includes aapt/AndroidManifest.xml

### LINKED ISSUE #22: Migrating app to Androidx fails due to unability to transform bottomsheet-1.3.1 dependency
Hi there.
As of today many faced an issue with building RN apps due to major release by google.
Details are here: [`RN issue`](https://github.com/facebook/react-native/issues/25293)

The main way to fix this is to upgrade your app to Androidx.
Android studio has a way to update dependencies sort of automatically, but bottomsheet is one that can not be updated.

Here is Gradle sync error after one adds 

`android.useAndroidX=true
android.enableJetifier=true`

to gradle.properties according to manual.

`Unable to resolve dependency for ':react-native-bottomsheet@debug/compileClasspath': Failed to transform file 'bottomsheet-1.3.1.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform`

This prevents me from migrating project to Androidx and thus from ability to further build.

I see this references native bottomsheet library and not your wrapper directly.
Hopefully you might know the reason Jettifier can not transform this exact aar or have other thoughts on this.

### PR DESCRIPTION
**Pull request by mikehardy**
I removed it, re-packed it, put it in android/libs and referenced it from libs
The dependency is effectively dead / unsupported anyway, so should not be
a maintenance burden

Fixes #22 

Demonstrated working at https://github.com/mikehardy/rn-androidx-demo / https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh#L34

### CODE REVIEW

**Comment by mikehardy** [comment]
I should mention, if you don't trust me enough to take my binary aar file (and who am I anyway?? don't trust me!) the alteration to the aar was:

```bash
mkdir temp && cd temp
jar -xvf ../bottomsheet-1.3.1.aar && rm ../bottomsheet-1.3.1.aar
\rm -fr aapt # This is the fix, aapt/AndroidManifest.xml is the problem
jar -cvf ../bottomsheet-1.3.1.aar *
```

Then just throw that in android/libs and reference it like so in the gradle.

**Comment by mikehardy** [comment]
@Doko-Demo-Doa I think this will fix the dependency for your library so you're library users are ready for AndroidX if they want

**Comment by Doko-Demo-Doa** [comment]
Sure, let me check and do the merging.

**Comment by Doko-Demo-Doa** [comment]
Thank you. Your implementation works well. v2.0.1 pushed with crashing issue fixed too.

**Comment by JerakRus** [comment]
It seems in version 2.2.0 this error occurs again, or something very similar.
Снимок экрана 2020-12-02 в 10 42 35

react-native:0.63.4
react-native-bottomsheet: 2.2.0

I just ran `./gradlew assembleRelease` in my project.

UPD: I downgraded back to 2.0.1 but the problem persists. It seems to be a matter of updating react-native. 
Then I decided to look into the library files, and find out what is outdated there. Here's what I saw: we use android.permission.SYSTEM_ALERT_WINDOW and here's some [information](https://www.xda-developers.com/android-q-system-alert-window-deprecate-bubbles/#:~:text=But%20in%20a%20future%20Android,in%20Android%20Q%20beta%202.&text=However%2C%20Bubbles%20are%20a%20part,a%20full%20replacement%20for%20SYSTEM_ALERT_WINDOW.) on it. Complete obsolescence just happens on android api 29, which uses react-native 0.63. It is not entirely clear why the problem did not appear earlier, but it seems in any case the library has no future, because the alternative that Google offers us does not have the necessary functionality.

P.s. Perhaps someone who is better versed in native code than me will look at this and say that I'm wrong. I'll be glad if this is so, but so far I realized that things are bad here.

P.s.s. Apparently the problem is still different from the original one, and I should have opened new issues, but I beg your pardon, I don't have much time for this now.

**Comment by Doko-Demo-Doa** [comment]
I see. I think it's better to fork another lib instead of continuing to use current one. Any suggestions?

**Comment by Doko-Demo-Doa** [comment]
2.5.2 released and it should be what you are looking for.

**Pull request merged**
